/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apd;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        FileProcessor fp1 = FileProcessor.getInstance("my_file1.txt");
        fp1.readFile();
        System.out.println("fp1 uuid = "+fp1.getUuid());

        FileProcessor fp2 = FileProcessor.getInstance("my_file2.txt");
        fp2.writeFile("my dummy data");
        System.out.println("fp2 uuid = "+fp2.getUuid());
    }
}
